name: Build Docker Image

on:
  push:
    branches: [main]
  

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug directory structure
        run: |
          ls -la
          pwd
          find . -type f  # List all files in the repo
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: login to docker hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: SocialMediaBot/
          
          push: true
          tags: mahannezafat/social-media-bot:latest
